package rebue.pfm.mo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   动作信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PFM_ACTI
 *
 * @mbg.generated do_not_delete_during_merge 2018-07-28 15:15:41
 */
@ApiModel(value = "PfmActiMo", description = "动作信息")
@JsonInclude(Include.NON_NULL)
public class PfmActiMo implements Serializable {

    /**
     * Database Column Remarks:
     *   动作ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "动作ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   系统ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.SYS_ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "系统ID")
    private String sysId;

    /**
     * Database Column Remarks:
     *   功能ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.FUNC_ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "功能ID")
    private Long funcId;

    /**
     * Database Column Remarks:
     *   动作名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.NAME
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "动作名称")
    private String name;

    /**
     * Database Column Remarks:
     *   是否鉴权
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.IS_AUTH
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "是否鉴权")
    private Boolean isAuth;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.IS_ENABLED
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "是否启用")
    private Boolean isEnabled;

    /**
     * Database Column Remarks:
     *   顺序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.ORDER_NO
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "顺序号")
    private Byte orderNo;

    /**
     * Database Column Remarks:
     *   动作备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI.REMARK
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @ApiModelProperty(value = "动作备注")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.ID
     *
     * @return the value of PFM_ACTI.ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.ID
     *
     * @param id the value for PFM_ACTI.ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.SYS_ID
     *
     * @return the value of PFM_ACTI.SYS_ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.SYS_ID
     *
     * @param sysId the value for PFM_ACTI.SYS_ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.FUNC_ID
     *
     * @return the value of PFM_ACTI.FUNC_ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public Long getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.FUNC_ID
     *
     * @param funcId the value for PFM_ACTI.FUNC_ID
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setFuncId(Long funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.NAME
     *
     * @return the value of PFM_ACTI.NAME
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.NAME
     *
     * @param name the value for PFM_ACTI.NAME
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.IS_AUTH
     *
     * @return the value of PFM_ACTI.IS_AUTH
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public Boolean getIsAuth() {
        return isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.IS_AUTH
     *
     * @param isAuth the value for PFM_ACTI.IS_AUTH
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setIsAuth(Boolean isAuth) {
        this.isAuth = isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.IS_ENABLED
     *
     * @return the value of PFM_ACTI.IS_ENABLED
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.IS_ENABLED
     *
     * @param isEnabled the value for PFM_ACTI.IS_ENABLED
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.ORDER_NO
     *
     * @return the value of PFM_ACTI.ORDER_NO
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public Byte getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.ORDER_NO
     *
     * @param orderNo the value for PFM_ACTI.ORDER_NO
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setOrderNo(Byte orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI.REMARK
     *
     * @return the value of PFM_ACTI.REMARK
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI.REMARK
     *
     * @param remark the value for PFM_ACTI.REMARK
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sysId=").append(sysId);
        sb.append(", funcId=").append(funcId);
        sb.append(", name=").append(name);
        sb.append(", isAuth=").append(isAuth);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PfmActiMo other = (PfmActiMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 15:15:41
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}
