package rebue.pfm.mo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   动作菜单
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PFM_ACTI_MENU
 *
 * @mbg.generated do_not_delete_during_merge 2018-07-28 16:10:10
 */
@ApiModel(value = "PfmActiMenuMo", description = "动作菜单")
@JsonInclude(Include.NON_NULL)
public class PfmActiMenuMo implements Serializable {

    /**
     * Database Column Remarks:
     *   动作菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI_MENU.ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    @ApiModelProperty(value = "动作菜单ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   动作ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI_MENU.ACTI_ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    @ApiModelProperty(value = "动作ID")
    private Long actiId;

    /**
     * Database Column Remarks:
     *   菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_ACTI_MENU.MENU_ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    @ApiModelProperty(value = "菜单ID")
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI_MENU.ID
     *
     * @return the value of PFM_ACTI_MENU.ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI_MENU.ID
     *
     * @param id the value for PFM_ACTI_MENU.ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI_MENU.ACTI_ID
     *
     * @return the value of PFM_ACTI_MENU.ACTI_ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    public Long getActiId() {
        return actiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI_MENU.ACTI_ID
     *
     * @param actiId the value for PFM_ACTI_MENU.ACTI_ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    public void setActiId(Long actiId) {
        this.actiId = actiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_ACTI_MENU.MENU_ID
     *
     * @return the value of PFM_ACTI_MENU.MENU_ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_ACTI_MENU.MENU_ID
     *
     * @param menuId the value for PFM_ACTI_MENU.MENU_ID
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", actiId=").append(actiId);
        sb.append(", menuId=").append(menuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PfmActiMenuMo other = (PfmActiMenuMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:10:10
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}
