package rebue.pfm.mo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   菜单信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PFM_MENU
 *
 * @mbg.generated do_not_delete_during_merge 2018-07-28 16:22:22
 */
@ApiModel(value = "PfmMenuMo", description = "菜单信息")
@JsonInclude(Include.NON_NULL)
public class PfmMenuMo implements Serializable {

    /**
     * Database Column Remarks:
     *   菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.ID
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "菜单ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   系统ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.SYS_ID
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "系统ID")
    private String sysId;

    /**
     * Database Column Remarks:
     *   菜单编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.CODE
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "菜单编码")
    private String code;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.NAME
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "菜单名称")
    private String name;

    /**
     * Database Column Remarks:
     *   路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.PATH
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "路径")
    private String path;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.IS_ENABLED
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "是否启用")
    private Boolean isEnabled;

    /**
     * Database Column Remarks:
     *   菜单图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.ICON
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "菜单图标")
    private String icon;

    /**
     * Database Column Remarks:
     *   菜单备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PFM_MENU.REMARK
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @ApiModelProperty(value = "菜单备注")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.ID
     *
     * @return the value of PFM_MENU.ID
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.ID
     *
     * @param id the value for PFM_MENU.ID
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.SYS_ID
     *
     * @return the value of PFM_MENU.SYS_ID
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.SYS_ID
     *
     * @param sysId the value for PFM_MENU.SYS_ID
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.CODE
     *
     * @return the value of PFM_MENU.CODE
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.CODE
     *
     * @param code the value for PFM_MENU.CODE
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.NAME
     *
     * @return the value of PFM_MENU.NAME
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.NAME
     *
     * @param name the value for PFM_MENU.NAME
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.PATH
     *
     * @return the value of PFM_MENU.PATH
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.PATH
     *
     * @param path the value for PFM_MENU.PATH
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.IS_ENABLED
     *
     * @return the value of PFM_MENU.IS_ENABLED
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.IS_ENABLED
     *
     * @param isEnabled the value for PFM_MENU.IS_ENABLED
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.ICON
     *
     * @return the value of PFM_MENU.ICON
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.ICON
     *
     * @param icon the value for PFM_MENU.ICON
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFM_MENU.REMARK
     *
     * @return the value of PFM_MENU.REMARK
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFM_MENU.REMARK
     *
     * @param remark the value for PFM_MENU.REMARK
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sysId=").append(sysId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", path=").append(path);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", icon=").append(icon);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PfmMenuMo other = (PfmMenuMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}
