package rebue.pfm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import rebue.pfm.mo.PfmActiUrnMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface PfmActiUrnMapper extends MybatisBaseMapper<PfmActiUrnMo, Long> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insert(PfmActiUrnMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insertSelective(PfmActiUrnMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    PfmActiUrnMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKeySelective(PfmActiUrnMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKey(PfmActiUrnMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmActiUrnMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmActiUrnMo> selectSelective(PfmActiUrnMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_URN
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existSelective(PfmActiUrnMo record);

    /**
     *  根据动作Ｉｄ删除动作链接
     *  @return
     */
    @Delete("delete from PFM_ACTI_URN where ACTI_ID = #{actiId,jdbcType=BIGINT}")
    int deleteByActiId(@Param("actiId") long actiId);
}
