package rebue.pfm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import rebue.pfm.mo.PfmActiMenuMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface PfmActiMenuMapper extends MybatisBaseMapper<PfmActiMenuMo, Long> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insert(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insertSelective(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    PfmActiMenuMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKeySelective(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKey(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmActiMenuMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmActiMenuMo> selectSelective(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existSelective(PfmActiMenuMo record);

    /**
     *  根据动作ｉｄ删除动作菜单
     *  @param actiId
     *  @return
     */
    @Delete("DELETE FROM PFM_ACTI_MENU WHERE ACTI_ID = #{actiId,jdbcType=BIGINT}")
    int deleteByActiId(@Param("actiId") long actiId);
}
