package rebue.pfm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.pfm.mo.PfmActiMenuMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface PfmActiMenuMapper extends MybatisBaseMapper<PfmActiMenuMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    int insert(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    int insertSelective(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    PfmActiMenuMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    int updateByPrimaryKeySelective(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    int updateByPrimaryKey(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    List<PfmActiMenuMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    List<PfmActiMenuMo> selectSelective(PfmActiMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI_MENU
     *
     * @mbg.generated 2018-07-24 10:36:02
     */
    boolean existSelective(PfmActiMenuMo record);
}