package rebue.pfm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;
import rebue.pfm.mo.PfmActiMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface PfmActiMapper extends MybatisBaseMapper<PfmActiMo, Long> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insert(PfmActiMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insertSelective(PfmActiMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    PfmActiMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKeySelective(PfmActiMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKey(PfmActiMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmActiMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmActiMo> selectSelective(PfmActiMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_ACTI
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existSelective(PfmActiMo record);

    @Update("UPDATE PFM_ACTI SET IS_ENABLED=#{isEnabled,jdbcType=TINYINT} WHERE ID=#{id,jdbcType=BIGINT}")
    int enabledActionOrNot(@Param("id") Long id, @Param("isEnabled") boolean isEnabled);
}
