package rebue.pfm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import rebue.pfm.mo.PfmMenuMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface PfmMenuMapper extends MybatisBaseMapper<PfmMenuMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	int insert(PfmMenuMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	int insertSelective(PfmMenuMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	PfmMenuMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	int updateByPrimaryKeySelective(PfmMenuMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	int updateByPrimaryKey(PfmMenuMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	List<PfmMenuMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	List<PfmMenuMo> selectSelective(PfmMenuMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PFM_MENU
	 *
	 * @mbg.generated 2018-07-24 10:36:02
	 */
	boolean existSelective(PfmMenuMo record);

	/**
	 * 是否启用菜单
	 * 
	 * @return
	 */
	@Update("UPDATE PFM_MENU SET IS_ENABLED=#{isEnabled,jdbcType=TINYINT} WHERE ID=#{id,jdbcType=BIGINT}")
	int whetherToEnableMenu(@Param("id") Long id, @Param("isEnabled") boolean isEnabled);

	/**
	 * 根据ｃｏｄｅ删除菜单
	 * @param code
	 * @return
	 */
	@Delete("DELETE FROM PFM_MENU WHERE CODE LIKE '${code}%'")
	int deleteByCode(@Param("code") String code);
}