package rebue.pfm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;
import rebue.pfm.mo.PfmMenuMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface PfmMenuMapper extends MybatisBaseMapper<PfmMenuMo, Long> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insert(PfmMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int insertSelective(PfmMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    PfmMenuMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKeySelective(PfmMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    int updateByPrimaryKey(PfmMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmMenuMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    List<PfmMenuMo> selectSelective(PfmMenuMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_MENU
     *
     * @mbg.generated 2018-07-28 16:22:22
     */
    boolean existSelective(PfmMenuMo record);

    /**
     *  是否启用菜单
     *
     *  @return
     */
    @Update("UPDATE PFM_MENU SET IS_ENABLED=#{isEnabled,jdbcType=TINYINT} WHERE CODE LIKE '${code}%'")
    int whetherToEnableMenu(@Param("code") String code, @Param("isEnabled") boolean isEnabled);

    /**
     *  根据ｃｏｄｅ删除菜单
     *  @param code
     *  @return
     */
    @Delete("DELETE FROM PFM_MENU WHERE CODE LIKE '${code}%'")
    int deleteByCode(@Param("code") String code);
}
