package rebue.pfm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.pfm.mo.PfmUserRoleMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface PfmUserRoleMapper extends MybatisBaseMapper<PfmUserRoleMo, Long> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    int insert(PfmUserRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    int insertSelective(PfmUserRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    PfmUserRoleMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    int updateByPrimaryKeySelective(PfmUserRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    int updateByPrimaryKey(PfmUserRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    List<PfmUserRoleMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    List<PfmUserRoleMo> selectSelective(PfmUserRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PFM_USER_ROLE
     *
     * @mbg.generated 2018-07-28 15:15:40
     */
    boolean existSelective(PfmUserRoleMo record);
}
