package rebue.pfm.ro;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import rebue.pfm.mo.PfmActiMenuMo;

@JsonInclude(Include.NON_NULL)
public class PfmActiMenuRo {

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	返回的结果值
     *
     * 	@mbg.generated
     */
    private PfmActiMenuMo record;

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public void setResult(Byte result) {
        this.result = result;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public PfmActiMenuMo getRecord() {
        return record;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public void setRecord(PfmActiMenuMo record) {
        this.record = record;
    }

    private int result;

    private String msg;

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    @Override
    public String toString() {
        return "PfmActiMenuRo [result=" + result + ", msg=" + msg + "]";
    }
}
