package rebue.pfm.ro;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import rebue.pfm.mo.PfmRoleActiMo;

@JsonInclude(Include.NON_NULL)
public class PfmRoleActiRo {

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	返回的结果值
     *
     * 	@mbg.generated
     */
    private PfmRoleActiMo record;

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public void setResult(Byte result) {
        this.result = result;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public PfmRoleActiMo getRecord() {
        return record;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public void setRecord(PfmRoleActiMo record) {
        this.record = record;
    }

    /**
     *  1:成功 -1:失败
     */
    private int result;

    /**
     *  返回值
     */
    private String msg;

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    @Override
    public String toString() {
        return "PfmRoleActiRo [result=" + result + ", msg=" + msg + "]";
    }
}
